package main

import (
	"log"
	"net/http"

	"github.com/gorilla/mux"
	"github.com/jeypc/go-restapi-mux/controllers/productcontroller"
	"github.com/jeypc/go-restapi-mux/models"

	// "github.com/swaggo/http-swagger"
	// _ "swagger-mux/docs"

	"github.com/go-chi/chi"
	"github.com/swaggo/http-swagger/v2"
	_ "github.com/swaggo/http-swagger/example/go-chi/docs" // docs is generated by Swag CLI, you have to import it.
)

func main() {
	models.ConnectDatabase()

	// Routing
	r := mux.NewRouter().StrictSlash(true)

	r.HandleFunc("/products", productcontroller.Index).Methods("GET")
	r.HandleFunc("/products/{id}", productcontroller.Show).Methods("GET")
	r.HandleFunc("/products", productcontroller.Create).Methods("POST")
	r.HandleFunc("/products/{id}", productcontroller.Update).Methods("PUT")
	r.HandleFunc("/products", productcontroller.Delete).Methods("DELETE")

	// Documentation
	r.PathPrefix("/documentation/").Handler(httpSwagger.WrapHandler)

	log.Fatal(http.ListenAndServe(":8080", r))
} 